version: '3'
services:
  redis-cache:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: kenji
      RABBITMQ_DEFAULT_PASS: 123456